server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customerms
          uri: lb://customerms
          predicates:
            - Path=/customers/**
        - id: productms
          uri: lb://productms
          predicates:
            - Path=/products/**
        - id: shoppingms
          uri: lb://shoppingms
          predicates:
            - Path=/invoices/**